# Generated by Django 5.1.1 on 2025-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
