# Generated by Django 5.2.1 on 2025-05-23 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='evidencia',
        ),
        migrations.CreateModel(
            name='FloraFauna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Flora', 'Flora'), ('Fauna', 'Fauna')], max_length=10)),
                ('nombre_especie', models.CharField(max_length=80)),
                ('descripcion', models.TextField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='flora_fauna/')),
                ('estado', models.CharField(default='Reportado', max_length=250)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.zona')),
            ],
            options={
                'verbose_name': 'Flora y Fauna',
                'verbose_name_plural': 'Flora y Fauna',
            },
        ),
        migrations.CreateModel(
            name='ImagenEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
                ('link_imagen', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='aplicacion.evidencia')),
            ],
            options={
                'verbose_name': 'Imagen de Evidencia',
                'verbose_name_plural': 'Imágenes de Evidencias',
            },
        ),
        migrations.DeleteModel(
            name='FaunaFlora',
        ),
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
