# Generated by Django 5.2.1 on 2025-05-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_imagen_evidencia_florafauna_imagenevidencia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FloraFauna',
            new_name='FaunaFlora',
        ),
        migrations.AlterModelOptions(
            name='faunaflora',
            options={'verbose_name': 'Fauna y Flora', 'verbose_name_plural': 'Fauna y Flora'},
        ),
    ]
