# Generated by Django 5.2.1 on 2025-05-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rename_florafauna_faunaflora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faunaflora',
            name='imagen',
        ),
        migrations.AddField(
            model_name='faunaflora',
            name='imagen_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faunaflora',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='faunaflora',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.zona'),
        ),
    ]
